name: CI

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: npm install
        run: npm install
      - name: npm run build
        run: npm run build
      - name: npm run test
        run: npm run test
        env:
          CI: true
